playersRaw = {
  "players": [
    "Csima Viktor, Hamar Csaba, Kiss Attila, Kocsor Péter, Németi Norbert, Villy Róbert",
    "Andódy Tibor, Buday Gyula, Gyergyák György, Herendi Tamás, Hídvégi Lajos, József István, Mány Péter, Németh Gusztáv, Papp Endre, Pirisi István, Szopkó János",
    "Komlódi Ferenc, Mayer János, Süveges Antal, Szöllősi Sándor, id.Vígh György, ifj.Vígh György, Vígh Zoltán",
    "Barna István, Dénes Pál, Hittmann László, dr.Páczay György, Pöstyéni Ferenc, Tar Csaba",
    "Duhonyiné Varsányi Anikó, dr.Fazekas István, Fazekas Róbert, Hatházi István, Juhász Gergő, Marjai Viktor, Szőts Viktor, Tokai Imre",
    "Aranyi Gabriella, Ardai Emese, Bulla József, Kovács Viktória, Stroh Tamás, Szabó Géza, Szabó György, Takács János, Takácsné Beke Judit",
    "Balkovics Áron, Domokos Bence, Gyöngyössy György, Hajdú Ákos, Karikás Gábor, Krebs Levente, Szabó Ádám, Tiszay Ádám, Vári-Kakas Andor",
    "Czibulya Bence, Fraknói Tamás, Jeszenszky Katalin, Katona István",
    "Alaksa Levente, Kolozsvári Bálint, ifj.Metykó László, Pallagi Patrik, Strobel Soma, Schubert Balázs",
    "Káli Sándor, Lökös Árpád, Révfy Tibor, Varga Mihály",
    "G.Szalai István, Hencz Ferenc Zoltán, Kabók József, Németh László, Németh Sándor, Ország Aranka, Pfeil Gyula",
    "Bárd Attila, Bauer Péter, Király Krisztián, Klausz Zoltán, Nagy László, Radó Róbert",
    "Galovics Márk, Kelemen Gyula, Pénzes Károly, Sprok Antal, Zöldy Béla",
    "Deák Péter, Haszpra Zsolt, dr.Klekner Péter, Kis György, Lakos Gábor, Surányi Tamás, Szűcsné dr.Sólya Zsuzsanna, Tóth Mónika",
    "Bozsó József, Herendi-Szabó Csilla, Héjj Ádám, Lökös László, Németh Péter, Szigeti Szonja, Tamásovits Ádám, Tóth László",
    "Csipák Péter, Czinder Mózes, Jáni Nándor, Keresztesi László, dr.Lövétei István, Magyar Viktória, id.Turbók Attila, Várnai Viktor",
    "Bacskó Ádám, Csank Zsuzsanna, Csortos Tibor, Kollár László, Rakoncza Gábor, Schwarcz Sándor, Szabó Gábor",
    "Lengyel Zoltán, Németh Attila, Riesenberger Ernő, Szabó Kálmán, Szávuly Miklós",
    "Béla Tamás, dr.Bodon Ferenc, dr.Kék László, Nyilas Attila",
    "Herendi Gábor, Jónás Gábor, Máté Győző,",
    "Petőházi Imola, Rónaszéki László, Séra Lajos, Széll Péter, Wéber Ferenc",
    "Droppán Béla, Szentiványi Ildikó, Takács Attila, Takács Gábor, Takács Lajos, Takács Réka",
    "Domokos Róbert, Gulya Endre, Gyuris József, Juhász József, Marton József, Perjési László, Somogyi Ferenc",
    "Farkas Attila, Knakker Norbert, dr.Lengyel Csilla, Nagy Gábor, Nagy Tibor",
    "Ángyán Károly, Bacsó Tiborné, Csetneky Attila, Gellén József, Holhos Sándor, Kovács Attila, Lázár Zsolt, Mitropulos Zoltán, Orosz Péter, Tatai Tamás, Zubonyai János",
    "dr.Csintalan László, Grynaeus László, Holecz Barna, Katona Ferenc, Kiss Norbert, Ludányi László, Németh András, Nyéki János, Simon Pál, Székely Ágnes, Tóbiás Zoltán, Tusa Györgyi",
    "Bot László, Dániel János, Fritz Tamás, Gombos Ákos, Lehel László, Majoros József, Marosi Katalin, dr.Marosi Viktória, Sólyomi Péter, Széky Andor",
    "Béres Sándor, Bíró István, Kőszegi János, Pálfy Gyula, Palkó Gábor, Piros Tamás, Romhányi Ádám, Steinbach Rajmund, Tóth Ferenc",
    "Bleitner Attila, Cseresznyés József, Király Attila, Szabó László, Szíjj László",
    "Almásy Károly, Csiszár János, Fekete Imre, Melis Ferenc, Szente József",
    "Borsodi Gábor, Gubi Róbert, Kovács Zoltán, Móricz Zsuzsanna",
    "Csizmazia Zsolt, Gut József, Kapitány Ferenc, Kiesswetter Ágoston, Réti Zoltán, Róka Gergely, Szabolcsi Ádám, Széplaky Zsolt,",
    "Tolnay Ádám,",
    "Tyukász Tamás",
    ", Zsitva Miklós",
    "Baligács Tamás, Dócziné Varga Szilvia, Kurtz Péterné, Mészáros Nikoletta, Oláh Zsuzsanna, Rimányi Mária, Süle Zoltán, Verebélyi Luca.",
    "Csizmás Kata, Fehérné Tihanyi Kata,",
    "Hegyi Csaba, Hittmann Márta, Papp Zoltán, Seprős Richárd, Szűcs Huba, Varga Lóránt",
    "Abaházi László, Bonnyai Adrienn, Dunavölgyi Zsolt, Puska László, Szabó Lajos, Szöllősi Norbert",
    "Borsi Eszter, Frisch Ruben, Hegedűs Bence, Janzsó Gergely, Kálnoky Diána Tímea, Márki Dániel, Márki Gergely, Márki László, Varga Mihály",
    "Balogh Csaba, Beke Ferenc, Bodroghy Bence, Erős László, Fekete Sándor, Fraknói Ádám, Füzesi István, Hanzi Elek, Holl László, Horváth Zoltán, dr.Kiss Lajos, Misch Attila, Misch Tamás, Pásztor Zsolt, dr.Pohl Ödön, Ravasz Zsolt, Rózsahegyi Péter, Szalai Erzsébet, Szénási Tamás, Tolnai Gábor, Uszkai László, Windischné Koskai Judit",
    "Algács Marcella, Gácsi Gergely, Hódi Emese, Magos Máté, Németh István, Szentgyörgyi-Horváth Bálint",
    "Buronyi Tibor, Csiba László, Décsi Sándor, Kis-Verbiczai József, Varga Gyula",
    "Baradziej Ákos, Borovszky Tamás, Juhász László, Kiss Dénes, Rákóczi Anita, Scherer Richárd, Südy Márton, Urbán Henriett, Valentini Ákos Tamás",
    "Dessewffy László, Kálmán László, id.Korsós Ferenc, ifj.Korsós Ferenc, Marlok Zoltán, Mészáros Ferenc, Szamosi György, Vikor Beatrix",
    "dr.Durst Gyöngyvér, Hajdú Henrietta, Koronghy Zsuzsanna, Krakkó Dániel, Strausz Dávid, Strausz Hajnalka, Strausz Imre, Strausz Krisztián,",
    "Földiné dr.Németh Zsuzsanna, Hódi Ágota, dr.Kiss Zoltán, Lantos Evelin, Mágori Ferencné, dr.Orbán Krisztina, Szebelédi János, Tímár-Geng György, Tóth Sámuel",
    "Endrődi Ferenc, Hahn György, Hanyecz József, Lakatosné Barna Veronika, Lovassy László, Mészáros István, Oláh Róbert, Pigler János, Vas Lajos",
    "Asbóth Csilla, Béres János, Fodorné Bajnok Aranka,",
    "Hermann Andrea, Józsa András, Kátsik László, Lakatos István, Lieber Mária Katalin",
    "Gergely Attila, Lajtrik Gábor, Nagy Zsolt, Paulik László, Stróbl György, Tari Ferenc",
    "Almagró Carmen, Czakó Zoltán, Huszain Inteiza, Katona László, Kéri Tamás, Rimóczi Gábor, Székelyné Burja Ilona, Tóth Irma",
    "Anastasia Ionova, Csővári Dániel, Galbáts Borisz, Leonardo Ferro, Márton Balázs, Pesti Pál, Viljanac Vanda, Dominic Ward",
    "Csonka Ferenc, Fütyü Lajos, Máté Andrea, Menyhárt Imre, Slobodan Matovic,",
    "dr.Békési Anikó, Bodnár Zoltán, Horváth József, Kalics József, Kiss László, Kristóf Sándor, Máté János, Matusek Adél, Molnárné Kovács Csilla, Polákovics Izabella, Sárközi Erzsébet, Séra Levente, Takács János",
    "Almási Bence, Finta András, Katona Dániel, Kristóf Pál, Leszták Kornél, Longo Paoló, Modrivich Máté, Nagy Rafael, Nagy Zoltán, Perlei Lóránt, Sokvári Olivér, Sólyomi Ádám, Sólyomi Tamás",
    "Bíró Imre, Dinai István, Harmath Dávid, Krén Pál, ifj.Pálfy Gyula, Palkó Gábor, Pánczél Barnabás, Serhokk Károly, Spala György, Spala Sára, Steinbach János, Szabó József, Terék Zoltán, Vargha Ákos, Vu Hong Nam",
    "Biczó Andrea,",
    "Dohány Zoltán, Fekete György, Gerlits Krisztián, Győri László, Homonyik Marcell, Johanidesz József, Kelecsényi Zoltán, Lengyel Károly, Pál László Bendegúz, Várhidi Zsuzsanna",
    "Fülöp Diána, Görbe Iván, Homonyik Attila, Orosz Gábor, Papp Zoltán, Szabó Helga, Szondi Tibor, Ványai-Kovács Sándor",
    "Aknai József, Börzsönyi Ágnes, Csekéné Szegedi Mónika,",
    "Dániel Barbara",
    ", Kalmár Gábor, Maior Norbert, dr.Szabados Péter"
  ],
  "team": [
    "Angyalföldi Meteor",
    "ANy. Biztonsági Nyomda SK II.",
    "Baross Gábor SK",
    "Belvárosi Asztalitenisz Egyesület II.",
    "Belvárosi Asztalitenisz Egyesület III.",
    "Budai XI SE IX.-Tömegsport",
    "BVSC-Zugló Sportiskola VI.",
    "Csepel-Sziget SE I.",
    "Csepel-Sziget SE II.",
    "Csepeli Vállalkozók Asztalitenisz Egyesülete II.",
    "Dunakanyar Asztalitenisz Sportkör",
    "Főnix SK",
    "Hidegkúti SC-Klebelsberg I.",
    "Hidegkúti SC-Klebelsberg II.",
    "Hidegkúti SC-Klebelsberg III.",
    "Igazságügyi Sport Club II.",
    "Jövőbarát SK",
    "Királynő SK",
    "Morgan Stanley SK I.",
    "mozgovideo.hu SK",
    "Mustármag SK I.",
    "Mustármag SK II.",
    "Pénzügyőr SE-Kutyaütők",
    "Pestújhelyi SC V.",
    "Puskás DSK-Csintalan-Párducok",
    "Puskás DSK-Csintalan-Tornádó",
    "Szent Pál akadémia SE I.",
    "Szigeti SK I.",
    "Szigeti SK II.",
    "Szivárvány BSK I.",
    "ÁNTSZ-Károlyi I.",
    "ÁNTSZ-Károlyi II.",
    "Belvárosi Asztalitenisz Egyesület IV.",
    "BKV Előre SC IV.",
    "Budai pingpong Klub",
    "Csepel-Sziget SE III.",
    "Csepel-Sziget SE IV.",
    "Csepeli Vállalkozók Asztalitenisz Egyesülete III.",
    "Dorsum SK",
    "Hidegkúti SC-Klebelsberg IV.",
    "Justitia SK",
    "Kancellária SE",
    "KFKI Petőfi SK VI.",
    "KFKI Petőfi SK női",
    "Külvárosi PC",
    "MTSE II.",
    "Morgan Stanley SK II.",
    "Multi Sportegyesület II.",
    "Pénzügyőr SE-Csilla-billa",
    "Puskás DSK-Csintalan-Csibék",
    "Szent Pál akadémia SE II.",
    "Szivárvány BSK II.",
    "Szivárvány BSK III.",
    "Tömegsport SK"
  ]
}
