roundsRaw = {
  "round": [
    "1.forduló, 2015.szeptember 7.-",
    "2.forduló -szeptember 14.-",
    "3.forduló -szeptember 21.-",
    "4.forduló -szeptember 28.-",
    "5.forduló -október 5.-",
    "6.forduló -október 12.-",
    "7.forduló -október 19.-",
    "8.forduló -október 26.-",
    "9.forduló -november 2.-",
    "10.forduló -november 9.-",
    "11.forduló -november 16.-",
    "12.forduló -november 23.-",
    "13.forduló -november 30.-",
    "14.forduló -december 7.-",
    "15.forduló -december 14.-"
  ],
  "matches": [
    "ANY Biztonsági Nyomda SK II. - PDSK-Csintalan-Tornádó 4:12",
    "Morgan Stanley SK I. - Szigeti SK I. 4:12",
    "Budai XI SE IX.-Tömegsport - Jövőbarát SK 7:9",
    "Királynő SK - Dunakanyar Asztalitenisz SK 13:3",
    "Igazságügyi Sport Club II. - Baross Gábor SK 12:4",
    "Csepel-Sziget SE II. - Hidegkúti SC-Klebelsberg II. 6:10",
    "Mustármag SK II. - Angyalföldi Meteor SK 13:3",
    "x - Belvárosi Asztalitenisz Egyesület III.",
    "Belvárosi Asztalitenisz Egyesület III. - Mustármag SK II.",
    "Angyalföldi Meteor SK - Csepel-Sziget SE II.",
    "Hidegkúti SC-Klebelsberg II. - Igazságügyi Sport Club II.",
    "Baross Gábor SK - Királynő SK",
    "Dunakanyar Asztalitenisz SK - Budai XI SE IX.-Tömegsport",
    "Jövőbarát SK - Morgan Stanley SK I.",
    "Szigeti SK I. - ANY Biztonsági Nyomda SK II.",
    "PDSK-Csintalan-Tornádó - x",
    "ANY Biztonsági Nyomda SK II. - Jövőbarát SK",
    "Morgan Stanley SK I. - Dunakanyar Asztalitenisz SK",
    "Budai XI SE IX.-Tömegsport - Baross Gábor SK",
    "Királynő SK - Hidegkúti SC-Klebelsberg II.",
    "Igazságügyi Sport Club II. - Angyalföldi Meteor SK",
    "Csepel-Sziget SE II. - Belvárosi Asztalitenisz Egyesület III.",
    "Mustármag SK II. - x",
    "PDSK-Csintalan-Tornádó - Szigeti SK I.",
    "Mustármag SK II. - PDSK-Csintalan-Tornádó",
    "x - Csepel-Sziget SE II.",
    "Belvárosi Asztalitenisz Egyesület III. - Igazságügyi Sport Club II.",
    "Angyalföldi Meteor SK - Királynő SK",
    "Hidegkúti SC-Klebelsberg II. - Budai XI SE IX.-Tömegsport",
    "Baross Gábor SK - Morgan Stanley SK I.",
    "Dunakanyar Asztalitenisz SK - ANY Biztonsági Nyomda SK II.",
    "Jövőbarát SK - Szigeti SK I.",
    "ANY Biztonsági Nyomda SK II. - Baross Gábor SK",
    "Morgan Stanley SK I. - Hidegkúti SC-Klebelsberg II.",
    "Budai XI SE IX.-Tömegsport - Angyalföldi Meteor SK",
    "Királynő SK - Belvárosi Asztalitenisz Egyesület III.",
    "Igazságügyi Sport Club II. - x",
    "Csepel-Sziget SE II. - Mustármag SK II.",
    "Szigeti SK I. - Dunakanyar Asztalitenisz SK",
    "PDSK-Csintalan-Tornádó - Jövőbarát SK",
    "Csepel-Sziget SE II. - PDSK-Csintalan-Tornádó",
    "Mustármag SK II. - Igazságügyi Sport Club II.",
    "x - Királynő SK",
    "Belvárosi Asztalitenisz Egyesület III. - Budai XI SE IX.-Tömegsport",
    "Angyalföldi Meteor SK - Morgan Stanley SK I.",
    "Hidegkúti SC-Klebelsberg II. - ANY Biztonsági Nyomda SK II.",
    "Baross Gábor SK - Szigeti SK I.",
    "Dunakanyar Asztalitenisz SK - Jövőbarát SK",
    "ANY Biztonsági Nyomda SK II. - Angyalföldi Meteor SK",
    "Morgan Stanley SK I. - Belvárosi Asztalitenisz Egyesület III.",
    "Budai XI SE IX.-Tömegsport - x",
    "Királynő SK - Mustármag SK II.",
    "Igazságügyi Sport Club II. - Csepel-Sziget SE II.",
    "Jövőbarát SK - Baross Gábor SK",
    "Szigeti SK I. - Hidegkúti SC-Klebelsberg II.",
    "PDSK-Csintalan-Tornádó - Dunakanyar Asztalitenisz SK",
    "Igazságügyi Sport Club II. - PDSK-Csintalan-Tornádó",
    "Csepel-Sziget SE II. - Királynő SK",
    "Mustármag SK II. - Budai XI SE IX.-Tömegsport",
    "x - Morgan Stanley SK I.",
    "Belvárosi Asztalitenisz Egyesület III. - ANY Biztonsági Nyomda SK II.",
    "Angyalföldi Meteor SK - Szigeti SK I.",
    "Hidegkúti SC-Klebelsberg II. - Jövőbarát SK",
    "Baross Gábor SK - Dunakanyar Asztalitenisz SK",
    "ANY Biztonsági Nyomda SK II. - x",
    "Morgan Stanley SK I. - Mustármag SK II.",
    "Budai XI SE IX.-Tömegsport - Csepel-Sziget SE II.",
    "Királynő SK - Igazságügyi Sport Club II.",
    "Dunakanyar Asztalitenisz SK - Hidegkúti SC-Klebelsberg II.",
    "Jövőbarát SK - Angyalföldi Meteor SK",
    "Szigeti SK I. - Belvárosi Asztalitenisz Egyesület III.",
    "PDSK-Csintalan-Tornádó - Baross Gábor SK",
    "Királynő SK - PDSK-Csintalan-Tornádó",
    "Igazságügyi Sport Club II. - Budai XI SE IX.-Tömegsport",
    "Csepel-Sziget SE II. - Morgan Stanley SK I.",
    "Mustármag SK II. - ANY Biztonsági Nyomda SK II.",
    "x - Szigeti SK I.",
    "Belvárosi Asztalitenisz Egyesület III. - Jövőbarát SK",
    "Angyalföldi Meteor SK - Dunakanyar Asztalitenisz SK",
    "Hidegkúti SC-Klebelsberg II. - Baross Gábor SK",
    "ANY Biztonsági Nyomda SK II. - Csepel-Sziget SE II.",
    "Morgan Stanley SK I. - Igazságügyi Sport Club II.",
    "Budai XI SE IX.-Tömegsport - Királynő SK",
    "Baross Gábor SK - Angyalföldi Meteor SK",
    "Dunakanyar Asztalitenisz SK - Belvárosi Asztalitenisz Egyesület III.",
    "Jövőbarát SK - x",
    "Szigeti SK I. - Mustármag SK II.",
    "PDSK-Csintalan-Tornádó - Hidegkúti SC-Klebelsberg II.",
    "Budai XI SE IX.-Tömegsport - PDSK-Csintalan-Tornádó",
    "Királynő SK - Morgan Stanley SK I.",
    "Igazságügyi Sport Club II. - ANY Biztonsági Nyomda SK II.",
    "Csepel-Sziget SE II. - Szigeti SK I.",
    "Mustármag SK II. - Jövőbarát SK",
    "x - Dunakanyar Asztalitenisz SK",
    "Belvárosi Asztalitenisz Egyesület III. - Baross Gábor SK",
    "Angyalföldi Meteor SK - Hidegkúti SC-Klebelsberg II.",
    "ANY Biztonsági Nyomda SK II. - Királynő SK",
    "Morgan Stanley SK I. - Budai XI SE IX.-Tömegsport",
    "Hidegkúti SC-Klebelsberg II. - Belvárosi Asztalitenisz Egyesület III.",
    "Baross Gábor SK - x",
    "Dunakanyar Asztalitenisz SK - Mustármag SK II.",
    "Jövőbarát SK - Csepel-Sziget SE II.",
    "Szigeti SK I. - Igazságügyi Sport Club II.",
    "PDSK-Csintalan-Tornádó - Angyalföldi Meteor SK",
    "Morgan Stanley SK I. - PDSK-Csintalan-Tornádó",
    "Budai XI SE IX.-Tömegsport - ANY Biztonsági Nyomda SK II.",
    "Királynő SK - Szigeti SK I.",
    "Igazságügyi Sport Club II. - Jövőbarát SK",
    "Csepel-Sziget SE II. - Dunakanyar Asztalitenisz SK",
    "Mustármag SK II. - Baross Gábor SK",
    "x - Hidegkúti SC-Klebelsberg II.",
    "Belvárosi Asztalitenisz Egyesület III. - Angyalföldi Meteor SK",
    "ANY Biztonsági Nyomda SK II. - Morgan Stanley SK I.",
    "Angyalföldi Meteor SK - x",
    "Hidegkúti SC-Klebelsberg II. - Mustármag SK II.",
    "Baross Gábor SK - Csepel-Sziget SE II.",
    "Dunakanyar Asztalitenisz SK - Igazságügyi Sport Club II.",
    "Jövőbarát SK - Királynő SK",
    "Szigeti SK I. - Budai XI SE IX.-Tömegsport",
    "PDSK-Csintalan-Tornádó - Belvárosi Asztalitenisz Egyesület III."
  ]
}
