teamsRaw = {
  "teams": [
    "Angyalföldi Meteor SK: X.kerület Porcelán utca 3-5. (Mavex terem) péntek 18.30 óra",
    "ANy. Biztonsági Nyomda SK II. : XIV.kerület Szőnyi út 2. (BVSC) csütörtök 18.30 óra",
    "ÁNTSZ-Károlyi I. : IV.kerület Erzsébet utca 69. (iskola) kedd 18.30 óra",
    "ÁNTSZ-Károlyi II. : IV.kerület Erzsébet utca 69. (iskola) kedd 18.30 óra",
    "Baross Gábor SK :",
    "I.kerület Kosciuszkó Tádé utca 3. (Lia iskola)",
    "hétfő 18.00 óra",
    "Belvárosi Asztalitenisz Egyesület II. : V.kerület Kálmán Imre utca 10. (alagsor) szerda 18.00 óra",
    "Belvárosi Asztalitenisz Egyesület III. : V.kerület Kálmán Imre utca 10. (alagsor) csütörtök 18.00 óra",
    "Belvárosi Asztalitenisz Egyesület IV. : V.kerület Kálmán Imre utca 10. (alagsor) kedd 18.00 óra",
    "BKV Előre SC IV. : X.kerület Fehér út 1/c. (BKV telephely, faház) csütörtök 18.00 óra",
    "Budai pingpong Klub :",
    "II.kerület Marczibányi tér 13. (Ormai László terem) péntek 18.30 óra",
    "Budai XI SE IX.-Tömegsport : II.kerület Marczibányi tér 13. (Ormai László terem) péntek 18.45 óra",
    "BVSC-Zugló Sportiskola VI. : XIV.kerület Szőnyi út 2. (BVSC) szerda 18.30 óra Csepel-Sziget SE I. : XXI.kerület Táncsics Mihály utca 92-96. (Jedlik Ányos gimnázium) szerda 17.30 óra",
    "Csepel-Sziget SE II. : XXI.kerület Táncsics Mihály utca 92-96. (Jedlik Ányos gimnázium) szerda 17.30 óra",
    "Csepel-Sziget SE III. : XXI.kerület Táncsics Mihály utca 92-96. (Jedlik Ányos gimnázium) péntek 17.30 óra",
    "Csepel-Sziget SE IV. : XXI.kerület Táncsics Mihály utca 92-96. (Jedlik Ányos gimnázium) hétfő 17.30 óra",
    "Csepeli Vállalkozók Asztalitenisz Egyesülete II. : XXI.kerület Központi út 17-19. szerda 18.00 óra",
    "Csepeli Vállalkozók Asztalitenisz Egyesülete III. : XXI.kerület Központi út 17-19. csütörtök 18.00 óra",
    "Csintalan-Csibék-Puskás DSK : XVI.kerület Újszász utca 108. (BGF) péntek 18.00 óra",
    "Csintalan-Párducok-Puskás DSK : XVI.kerület Újszász utca 108. (BGF) péntek 18.00 óra",
    "Csintalan-Tornádó-Puskás DSK : XVI.kerület Újszász utca 108. (BGF) szerda 18.00 óra",
    "Dorsum SK : VI.kerület Zichy Jenő utca 5. (alagsor) csütörtök 18.30 óra",
    "Dunakanyar Asztalitenisz Sportkör : XIV.kerület Róna utca 86-100. (Postás) csütörtök 18.00 óra",
    "Főnix SK : II.kerület Marczibányi tér 13. (Ormai László terem) csütörtök 18.30 óra",
    "Hidegkúti SC-Klebelsberg I. : II.kerület Templom utca 2-10. (közösségi ház) csütörtök 18.00 óra",
    "Hidegkúti SC-Klebelsberg II. : II.kerület Templom utca 2-10. (közösségi ház) péntek 18.00 óra",
    "Hidegkúti SC-Klebelsberg III. : II.kerület Templom utca 2-10. (közösségi ház) szerda 18.00 óra",
    "Hidegkúti SC-Klebelsberg IV. : II.kerület Templom utca 2-10. (közösségi ház) hétfő 17.45 óra",
    "Igazságügyi Sport Club II.: IX.kerület Bakáts tér 12. (iskola) péntek 17.45 óra",
    "Jövőbarát SK : III.kerület Pethe Ferenc tér 1-3. (közösségi ház) csütörtök 18.30 óra",
    "Justitia SK : IX.kerület Gyáli út 36. (Fkf Rt) péntek 18.00 óra",
    "Kancellária SE: II.kerület Zilah utca 3. (Budai Pingpong klub) kedd 18.30 óra",
    "KFKI Petőfi SK VI. : XII.kerület Konkoly Thege út 29-33. (KFKI sporttelep) csütörtök 18.30 óra",
    "KFKI Petőfi SK női : VII.kerület Istvánmezei út 1-3. (KSI) hétfő 18.00 óra",
    "Királynő SK : XXII.kerület Anna utca 13-15. (BNA gimnázium) péntek 17.30 óra",
    "Külvárosi PC :",
    "IV.kerület Váci út 102. (Vízművek Rt. sporttelep) csütörtök 18.00 óra",
    "MTSE II. : I.kerület Kosciuszkó Tádé utca 3. (Lia iskola) kedd 18.00 óra",
    "Morgan Stanley SK I. :",
    "VIII.kerület Elnök utca 1. (Asztalitenisz egyetem) kedd 18.30 óra",
    "Morgan Stanley SK II. :",
    "VIII.kerület Elnök utca 1. (Asztalitenisz egyetem) szerda 18.30 óra",
    "mozgovideo.hu SK : XII.kerület Konkoly Thege út 29-33. (KFKI sporttelep) hétfő 18.00 óra",
    "Multi SE II.: XIV.kerület Szőnyi út 2. (BVSC) hétfő 18.00 óra",
    "Mustármag SK I. :",
    "III.kerület Templom utca 3-5. (iskola) csütörtök 17.30 óra",
    "Mustármag SK II. :",
    "III.kerület Templom utca 3-5. (iskola) csütörtök 17.30 óra",
    "Pénzügyőr SE-Csilla-billa: VIII.kerület Elnök utca 1. (Joó-pont) szerda 18.00 óra",
    "Pénzügyőr SE-Kutyaütők: VIII.kerület Elnök utca 1. (Joó-pont) hétfő 18.00 óra",
    "Pestújhelyi SC V.: XV.kerület Szűcs István utca 45. (közössági ház) szerda 18.00 óra",
    "Szent Pál Akadémia I. : X.kerület Száva utca 1-3. (gimnázium) kedd 18.00 óra",
    "Szent Pál Akadémia II. : X.kerület Száva utca 1-3. (gimnázium) kedd 17.45 óra",
    "Szigeti ISK I.: IV.kerület Szigeti József utca 1-3. (iskola) kedd 18.00 óra",
    "Szigeti ISK II.: IV.kerület Szigeti József utca 1-3. (iskola) csütörtök 17.45 óra",
    "Szivárvány BSK I. : X.kerület Porcelán utca 3-5. (Mavex terem) szerda 18.30 óra",
    "Szivárvány BSK II. : X.kerület Porcelán utca 3-5. (Mavex terem) szerda 18.30 óra",
    "Szivárvány BSK III. : X.kerület Porcelán utca 3-5. (Mavex terem) szerda 18.30 óra",
    "Tömegsport :",
    "I.kerület Kosciuszkó Tádé utca 3. (Lia iskola) kedd 18.00 óra",
  ]
};
